# Noctalia Theme for Mango
# Generated automatically by Noctalia

shadowscolor = 0x11111bff
rootcolor = 0x1e1e2eff
bordercolor = 0x6c7086ff
dropcolor = 0xf5e0dc80
splitcolor = 0xf9e2afff
focuscolor = 0xf5e0dcff
maximizescreencolor = 0xf2cdcdff
urgentcolor = 0xf38ba8ff
scratchpadcolor = 0xf9e2afff
globalcolor = 0xde5a40ff
overlaycolor = 0xdf2d2dff
jump_label_decorate_fg_color = 0xcdd6f4ff
jump_label_decorate_bg_color = 0x3a3b50ff
jump_label_decorate_focus_fg_color = 0x1e1e2eff
jump_label_decorate_focus_bg_color = 0xf5e0dcff
jump_label_decorate_border_color = 0x6c7086ff
group_bar_decorate_fg_color = 0xcdd6f4ff
group_bar_decorate_bg_color = 0x3a3b50ff
group_bar_decorate_focus_fg_color = 0x1e1e2eff
group_bar_decorate_focus_bg_color = 0xf5e0dcff
group_bar_decorate_border_color = 0x6c7086ff
