[bar]
order = [ "default", "islands" ]

    [bar.default]
    background_opacity = 0.79999998211860657
    capsule_radius = 0
    font_family = "Maple Mono NF"
    margin_ends = 0
    radius = 0

    [bar.islands]
    background_opacity = 0.0
    capsule = true
    capsule_fill = "surface"
    capsule_opacity = 0.79999998211860657
    capsule_radius = 0
    center = [ "cat", "date", "clock" ]
    concave_edge_corners = false
    enabled = true
    font_family = "Maple Mono NF"
    margin_ends = 0
    radius = 0

[dock]
background_opacity = 0.79999998211860657
concave_edge_corners = false
enabled = true
launcher_custom_image = "/usr/share/icons/cachyos.svg"
launcher_custom_image_colorize = true
launcher_position = "start"
radius = 0
reserve_space = false
smart_auto_hide = true

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@HDMI-A-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 1280.0
    cy = 1258.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[notification]
background_opacity = 0.79999998211860657

[osd]
background_opacity = 0.79999998211860657

[plugins]
enabled = [ "dotnetrob/cat", "noctalia/timer" ]

[shell]
corner_radius_scale = 0.0
font_family = "Maple Mono NF"
polkit_agent = true

    [shell.panel]
    transparency_mode = "soft"

[theme]
builtin = "Catppuccin"
community_palette = "Catppuccin Mocha Mauve-Lavender"
source = "builtin"

    [theme.templates]
    builtin_ids = [ "alacritty", "btop", "cava", "gtk3", "gtk4", "hyprland", "kcolorscheme", "kitty", "mango", "niri", "qt" ]
    community_ids = [
        "pywalfox",
        "discord",
        "blender",
        "gimp",
        "inkscape",
        "vscode",
        "heroiclauncher",
        "prismlauncher",
        "steam",
        "fastfetch",
        "hyprtoolkit",
        "papirus-icons",
        "bat",
        "lazygit"
    ]

[wallpaper.default]
path = "/usr/share/noctalia/assets/noctalia-wallpaper.png"

[wallpaper.last]
path = "/usr/share/noctalia/assets/noctalia-wallpaper.png"

[widget.cat]
type = "dotnetrob/cat:cat"

[widget.cat_2]
type = "dotnetrob/cat:cat"

[widget.clock]
format = "{:%I:%M %p} "

[widget.launcher]
custom_image = "/usr/share/icons/cachyos.svg"
custom_image_colorize = true

[widget.workspaces]
style = "minimal"
