[backdrop]
enabled = true

[bar]
order = [ "default", "islands", "islandsgroups" ]

    [bar.default]
    background_opacity = 0.79999998211860657
    capsule_radius = 0
    center = [ "cat_2", "cpu", "ram", "temp", "network_rx", "network_tx" ]
    end = [
        "media",
        "date",
        "clock",
        "eyecare-widget",
        "tray",
        "notifications",
        "clipboard",
        "network",
        "bluetooth",
        "volume",
        "colorscheme_variants_widget",
        "session"
    ]
    font_family = "Maple Mono NF"
    margin_edge = 8
    margin_ends = 8
    radius = 0
    start = [ "launcher", "wallpaper", "wallhaven", "workspaces", "active_window", "bar" ]

    [bar.islands]
    background_opacity = 0.0
    capsule = true
    capsule_border = "primary"
    capsule_fill = "surface"
    capsule_opacity = 0.79999998211860657
    capsule_radius = 0
    center = [ "cat", "cpu", "ram", "temp", "network_rx", "network_tx" ]
    concave_edge_corners = false
    enabled = false
    end = [
        "media",
        "date",
        "clock",
        "eyecare_widget_2",
        "tray",
        "notifications",
        "clipboard",
        "network",
        "bluetooth",
        "volume",
        "colorscheme_variants_widget_2",
        "control-center",
        "session"
    ]
    font_family = "Maple Mono NF"
    margin_ends = 0
    radius = 0
    start = [ "launcher", "wallpaper", "wallhaven_2", "workspaces", "active_window", "bar_2" ]

    [bar.islandsgroups]
    background_opacity = 0.0
    capsule = true
    capsule_border = "primary"
    capsule_fill = "surface"
    capsule_opacity = 0.79999998211860657
    capsule_radius = 0
    center = [ "group:g4" ]
    concave_edge_corners = false
    enabled = false
    end = [ "group:g3" ]
    margin_ends = 0
    radius = 0
    start = [ "group:g2" ]

        [[bar.islandsgroups.capsule_group]]
        accordion = false
        accordion_direction = "end"
        border = "primary"
        enabled = true
        fill = "surface"
        id = "g1"
        members = [ "launcher", "wallpaper", "workspaces", "wallhaven_2", "active_window", "bar_2" ]
        opacity = 0.79999995231628418
        padding = 6.0
        radius = 0.0

        [[bar.islandsgroups.capsule_group]]
        accordion = false
        accordion_direction = "end"
        border = "primary"
        enabled = true
        fill = "surface"
        id = "g3"
        members = [
            "media",
            "date",
            "clock",
            "eyecare_widget_2",
            "tray",
            "notifications",
            "clipboard",
            "network",
            "bluetooth",
            "volume",
            "brightness",
            "battery",
            "colorscheme_variants_widget_3",
            "control-center",
            "session"
        ]
        opacity = 0.79999995231628418
        padding = 6.0
        radius = 0.0

        [[bar.islandsgroups.capsule_group]]
        accordion = false
        accordion_direction = "end"
        border = "primary"
        enabled = true
        fill = "surface"
        id = "g4"
        members = [ "cat", "cpu", "temp", "ram", "network_rx", "network_tx" ]
        opacity = 0.79999995231628418
        padding = 6.0
        radius = 0.0

        [[bar.islandsgroups.capsule_group]]
        accordion = false
        accordion_direction = "end"
        border = "primary"
        enabled = true
        fill = "surface"
        id = "g2"
        members = [ "launcher", "wallpaper", "wallhaven_3", "workspaces", "active_window", "bar_3" ]
        opacity = 0.79999995231628418
        padding = 6.0
        radius = 0.0

[control_center]
sidebar_section = "none"

[dock]
background_opacity = 0.79999998211860657
enabled = true
launcher_custom_image = "/usr/share/icons/cachyos.svg"
launcher_custom_image_colorize = true
launcher_position = "start"
margin_edge = 8
pinned = [ "librewolf", "kitty", "org.gnome.Nautilus", "equibop", "vscodium" ]
radius = 0
reserve_space = false
show_dots = true
smart_auto_hide = true

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@HDMI-A-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 1280.0
    cy = 1152.0
    output = "HDMI-A-1"
    placement_height = 1152.0
    placement_width = 2048.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[notification]
background_opacity = 0.79999998211860657

[osd]
background_opacity = 0.79999998211860657

[plugin_settings."dotnetrob/cat"]
panel_placement = "floating"

[plugin_settings."noctalia/example"]
panel_open_near_click = true
panel_position = "auto"

[plugin_settings."noctalia/timer"]
panel_placement = "floating"

[plugin_settings."noctalia/wallhaven"]
browser_placement = "floating"
download_dir = "/home/ckjos/Pictures/Wallpapers/wallhaven"

[plugin_settings."uozzoku/colorscheme_variants"]
panel_placement = "floating"

[plugins]
auto_update = "all"
enabled = [
    "ezequiel/mango_layouts",
    "dotnetrob/cat",
    "noctalia/wallhaven",
    "apex077/eyecare",
    "noctalia/timer",
    "whyoolw/dropwall",
    "uozzoku/colorscheme_variants"
]

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/official-plugins"
    name = "official"

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/community-plugins"
    name = "community"

    [[plugins.source]]
    enabled = false
    kind = "git"
    location = "https://github.com/Mistake505/noctalia-colorscheme-variants-plugin.git"
    name = "me-plugins"

    [[plugins.source]]
    kind = "path"
    location = "/home/ckjos/Projects/me-plugins"
    name = "me-plugins-local"

[shell]
corner_radius_scale = 0.0
font_family = "Maple Mono NF"
niri_overview_type_to_launch_enabled = true
polkit_agent = true
time_format = "{:%I:%M %p}"

    [shell.launcher]
    categories = false

        [shell.launcher.providers.session]
        global = true

        [shell.launcher.providers.windows]
        global = true

    [shell.panel]
    control_center_placement = "floating"
    open_near_click_control_center = true
    open_near_click_session = true
    session_placement = "floating"
    transparency_mode = "soft"
    wallpaper_placement = "floating"

    [shell.session]
    grid = true

[theme]
builtin = "Tokyo-Night"
community_palette = "Rose Pine Moon"
custom_palette = "custom"
mode = "dark"
source = "builtin"
wallpaper_scheme = "faithful"

    [theme.templates]
    builtin_ids = [ "alacritty", "btop", "cava", "gtk3", "gtk4", "hyprland", "kcolorscheme", "kitty", "mango", "niri", "qt" ]
    community_ids = [
        "pywalfox",
        "discord",
        "blender",
        "gimp",
        "inkscape",
        "vscode",
        "zed",
        "heroiclauncher",
        "prismlauncher",
        "steam",
        "fastfetch",
        "obs",
        "papirus-icons",
        "bat",
        "lazygit"
    ]

[wallpaper.default]
path = "/home/ckjos/Pictures/Wallpapers/sel-walls_1/aesthetic.png"

[wallpaper.last]
path = "/home/ckjos/Pictures/Wallpapers/sel-walls_1/aesthetic.png"

[wallpaper.monitors.HDMI-A-1]
path = "/home/ckjos/Pictures/Wallpapers/sel-walls_1/aesthetic.png"

[widget.bar]
show_idle_on_horizontal = false
type = "noctalia/timer:bar"

[widget.bar_2]
show_idle_on_horizontal = false
type = "noctalia/timer:bar"

[widget.bar_3]
type = "noctalia/timer:bar"

[widget.cat]
type = "dotnetrob/cat:cat"

[widget.cat_2]
type = "dotnetrob/cat:cat"

[widget.clock]
format = "{:%I:%M %p}"

[widget.colorscheme_variants_widget]
type = "uozzoku/colorscheme_variants:colorscheme_variants_widget"

[widget.colorscheme_variants_widget_2]
type = "uozzoku/colorscheme_variants:colorscheme_variants_widget"

[widget.colorscheme_variants_widget_3]
type = "uozzoku/colorscheme_variants:colorscheme_variants_widget"

[widget.cpu]
visualization = "none"

[widget.eyecare-widget]
type = "apex077/eyecare:eyecare-widget"

[widget.eyecare_widget_2]
type = "apex077/eyecare:eyecare-widget"

[widget.launcher]
custom_image = "/usr/share/icons/cachyos.svg"
custom_image_colorize = true

[widget.network]
show_label = false

[widget.network_rx]
label_show_units = true
visualization = "none"

[widget.network_tx]
label_show_units = true
visualization = "none"

[widget.ram]
label_show_units = false
visualization = "none"

[widget.taskbar]
scale = 2.5

[widget.temp]
visualization = "none"

[widget.tray]
detached_panel = true
drawer = true

[widget.wallhaven]
type = "noctalia/wallhaven:wallhaven"

[widget.wallhaven_2]
type = "noctalia/wallhaven:wallhaven"

[widget.wallhaven_3]
type = "noctalia/wallhaven:wallhaven"

[widget.workspaces]
show_labels = false
