color0 #1c2836
color1 #fd4663
color2 #b1cff1
color3 #b7b5ed
color4 #d3bae8
color5 #93bcec
color6 #9996e9
color7 #f2f2f3
color8 #616971
color9 #fd4663
color10 #b1cff1
color11 #b7b5ed
color12 #d3bae8
color13 #93bcec
color14 #9996e9
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #151e29
background            #151e29
foreground            #f2f2f3
selection_foreground  #afb2b6
selection_background  #1c2836
active_border_color   #b1cff1
inactive_border_color #1c2836
url_color             #b1cff1

active_tab_foreground   #181e25
active_tab_background   #b1cff1
inactive_tab_foreground #afb2b6
inactive_tab_background #1c2836
cursor_trail_color      #afb2b6
